-- Migration: Add new achievement keys to enum
-- Date: 2025-11-24

-- Add new values to the achievementkey enum
ALTER TYPE achievementkey ADD VALUE IF NOT EXISTS 'LEVEL_20';
ALTER TYPE achievementkey ADD VALUE IF NOT EXISTS 'LEVEL_50';
ALTER TYPE achievementkey ADD VALUE IF NOT EXISTS 'FIRST_LOGIN';
ALTER TYPE achievementkey ADD VALUE IF NOT EXISTS 'CREATE_5_HABITS';
ALTER TYPE achievementkey ADD VALUE IF NOT EXISTS 'STREAK_30_DAYS';
ALTER TYPE achievementkey ADD VALUE IF NOT EXISTS 'STREAK_100_DAYS';
ALTER TYPE achievementkey ADD VALUE IF NOT EXISTS 'COMPLETE_10_TASKS';
ALTER TYPE achievementkey ADD VALUE IF NOT EXISTS 'COMPLETE_50_TASKS';
ALTER TYPE achievementkey ADD VALUE IF NOT EXISTS 'COMPLETE_100_TASKS';
ALTER TYPE achievementkey ADD VALUE IF NOT EXISTS 'COMPLETE_500_TASKS';
ALTER TYPE achievementkey ADD VALUE IF NOT EXISTS 'PERFECT_WEEK';
ALTER TYPE achievementkey ADD VALUE IF NOT EXISTS 'EARLY_BIRD';
ALTER TYPE achievementkey ADD VALUE IF NOT EXISTS 'NIGHT_OWL';
